name: 'Set up git-sdk-64-minimal'
description: 'Set up a minimal subset of the Git for Windows SDK for CI/PR testing'
author: 'dscho'
inputs:
  path:
    description: 'Destination ("git-sdk-64-minimal" will be unzipped into this directory)'
    required: false
    default: ${{runner.workspace}}
runs:
  using: 'node12'
  main: 'index.js'

